### ISSUE TITLE
Cucumber suite fails on 1.8.7, matahari works

### ISSUE THREAD

**Issue by rentalcustard** [rentalcustard/matahari#8]
```
$ bundle exec rake
/home/vagrant/.rvm/rubies/ruby-1.8.7-p334/bin/ruby -S bundle exec rspec ./spec/matahari/adapters/test_unit_spec.rb ./spec/matahari/adapters/rspec_spec.rb ./spec/matahari/invocation_matcher_spec.rb ./spec/matahari/spy_spec.rb
FFFF......../tmp/travis/builds/mortice/matahari/lib/matahari/spy.rb:11: warning: undefining `__send__' may cause serious problem
/tmp/travis/builds/mortice/matahari/lib/matahari/spy.rb:11: warning: undefining `__id__' may cause serious problem
/tmp/travis/builds/mortice/matahari/lib/matahari/spy.rb:11: warning: undefining `__send__' may cause serious problem
/tmp/travis/builds/mortice/matahari/lib/matahari/spy.rb:11: warning: undefining `__id__' may cause serious problem
F/tmp/travis/builds/mortice/matahari/lib/matahari/spy.rb:11: warning: undefining `__send__' may cause serious problem
/tmp/travis/builds/mortice/matahari/lib/matahari/spy.rb:11: warning: undefining `__id__' may cause serious problem
F/tmp/travis/builds/mortice/matahari/lib/matahari/spy.rb:11: warning: undefining `__send__' may cause serious problem
/tmp/travis/builds/mortice/matahari/lib/matahari/spy.rb:11: warning: undefining `__id__' may cause serious problem
F/tmp/travis/builds/mortice/matahari/lib/matahari/spy.rb:11: warning: undefining `__send__' may cause serious problem
/tmp/travis/builds/mortice/matahari/lib/matahari/spy.rb:11: warning: undefining `__id__' may cause serious problem
F/tmp/travis/builds/mortice/matahari/lib/matahari/spy.rb:11: warning: undefining `__send__' may cause serious problem
/tmp/travis/builds/mortice/matahari/lib/matahari/spy.rb:11: warning: undefining `__id__' may cause serious problem
F/tmp/travis/builds/mortice/matahari/lib/matahari/spy.rb:11: warning: undefining `__send__' may cause serious problem
/tmp/travis/builds/mortice/matahari/lib/matahari/spy.rb:11: warning: undefining `__id__' may cause serious problem
F/tmp/travis/builds/mortice/matahari/lib/matahari/spy.rb:11: warning: undefining `__send__' may cause serious problem
/tmp/travis/builds/mortice/matahari/lib/matahari/spy.rb:11: warning: undefining `__id__' may cause serious problem
F/tmp/travis/builds/mortice/matahari/lib/matahari/spy.rb:11: warning: undefining `__send__' may cause serious problem
/tmp/travis/builds/mortice/matahari/lib/matahari/spy.rb:11: warning: undefining `__id__' may cause serious problem
F/tmp/travis/builds/mortice/matahari/lib/matahari/spy.rb:11: warning: undefining `__send__' may cause serious problem
/tmp/travis/builds/mortice/matahari/lib/matahari/spy.rb:11: warning: undefining `__id__' may cause serious problem
F

Failures:

  1) Matahari::Adapters::TestUnit#assert_received with a passing test passes
     Failure/Error: @dummy = DummyTestCase.new "dummy"
     NameError:
       uncaught throw `invalid_test'
     # ./spec/matahari/adapters/test_unit_spec.rb:10:in `new'
     # ./spec/matahari/adapters/test_unit_spec.rb:10

  2) Matahari::Adapters::TestUnit#assert_received with a passing test with a failing test fails with an informative message
     Failure/Error: @dummy = DummyTestCase.new "dummy"
     NameError:
       uncaught throw `invalid_test'
     # ./spec/matahari/adapters/test_unit_spec.rb:10:in `new'
     # ./spec/matahari/adapters/test_unit_spec.rb:10

  3) Matahari::Adapters::TestUnit#assert_not_received with a passing test passes
     Failure/Error: @dummy = DummyTestCase.new "dummy"
     NameError:
       uncaught throw `invalid_test'
     # ./spec/matahari/adapters/test_unit_spec.rb:10:in `new'
     # ./spec/matahari/adapters/test_unit_spec.rb:10

  4) Matahari::Adapters::TestUnit#assert_not_received with a failing test fails with an informative message
     Failure/Error: @dummy = DummyTestCase.new "dummy"
     NameError:
       uncaught throw `invalid_test'
     # ./spec/matahari/adapters/test_unit_spec.rb:10:in `new'
     # ./spec/matahari/adapters/test_unit_spec.rb:10

  5) Spy takes an optional name parameter
     Failure/Error: named.name.should == :bond
     NoMethodError:
       undefined method `name' for #<Spy:0x7fbf98590df8>
     # ./spec/matahari/spy_spec.rb:8

  6) Spy in the field remains as a sleeper agent until called upon
     Failure/Error: lambda do
       expected no NoMethodError, got #<NoMethodError: undefined method `one' for #<Spy:0x7fbf9856ca48>>
     # ./spec/matahari/spy_spec.rb:15

  7) Spy in the field captures communications
     Failure/Error: mata_hari.one
     NoMethodError:
       undefined method `one' for #<Spy:0x7fbf98559ee8>
     # ./spec/matahari/spy_spec.rb:25

  8) Spy in the field captures the details of communications
     Failure/Error: mata_hari.one
     NoMethodError:
       undefined method `one' for #<Spy:0x7fbf98543698>
     # ./spec/matahari/spy_spec.rb:34

  9) Spy in the field returns nil on method_missing with no stubs
     Failure/Error: mata_hari.one.should be_nil
     NoMethodError:
       undefined method `one' for #<Spy:0x7fbf985320f0>
     # ./spec/matahari/spy_spec.rb:43

  10) Spy in the field doesn't stop you stubbing
     Failure/Error: mata_hari.stubs(:test) { "Hello" }
     NoMethodError:
       undefined method `stubs' for #<Spy:0x7fbf98523848>
     # ./spec/matahari/spy_spec.rb:49

  11) Spy in the field#has_received? with no iterator passed returns a debriefing with no restriction on times called
     Failure/Error: mata_hari.has_received?
     NoMethodError:
       undefined method `has_received?' for #<Spy:0x7fbf98515db0>
     # ./spec/matahari/spy_spec.rb:61

  12) Spy in the field#has_received? with an iterator passed returns a debriefing with a restriction on times called
     Failure/Error: mata_hari.has_received?(iterator)
     NoMethodError:
       undefined method `has_received?' for #<Spy:0x7fbf98504ba0>
     # ./spec/matahari/spy_spec.rb:70

  13) Spy in the field when a new method has been added to Object still works
     Failure/Error: mata_hari.new_method
     NoMethodError:
       undefined method `new_method' for #<Spy:0x7fbf984f2928>
     # ./spec/matahari/spy_spec.rb:87

Finished in 0.04157 seconds
21 examples, 13 failures

Failed examples:

rspec ./spec/matahari/adapters/test_unit_spec.rb:15 # Matahari::Adapters::TestUnit#assert_received with a passing test passes
rspec ./spec/matahari/adapters/test_unit_spec.rb:24 # Matahari::Adapters::TestUnit#assert_received with a passing test with a failing test fails with an informative message
rspec ./spec/matahari/adapters/test_unit_spec.rb:36 # Matahari::Adapters::TestUnit#assert_not_received with a passing test passes
rspec ./spec/matahari/adapters/test_unit_spec.rb:45 # Matahari::Adapters::TestUnit#assert_not_received with a failing test fails with an informative message
rspec ./spec/matahari/spy_spec.rb:4 # Spy takes an optional name parameter
rspec ./spec/matahari/spy_spec.rb:13 # Spy in the field remains as a sleeper agent until called upon
rspec ./spec/matahari/spy_spec.rb:22 # Spy in the field captures communications
rspec ./spec/matahari/spy_spec.rb:31 # Spy in the field captures the details of communications
rspec ./spec/matahari/spy_spec.rb:40 # Spy in the field returns nil on method_missing with no stubs
rspec ./spec/matahari/spy_spec.rb:46 # Spy in the field doesn't stop you stubbing
rspec ./spec/matahari/spy_spec.rb:58 # Spy in the field#has_received? with no iterator passed returns a debriefing with no restriction on times called
rspec ./spec/matahari/spy_spec.rb:66 # Spy in the field#has_received? with an iterator passed returns a debriefing with a restriction on times called
rspec ./spec/matahari/spy_spec.rb:84 # Spy in the field when a new method has been added to Object still works
rake aborted!
ruby -S bundle exec rspec ./spec/matahari/adapters/test_unit_spec.rb ./spec/matahari/adapters/rspec_spec.rb ./spec/matahari/invocation_matcher_spec.rb ./spec/matahari/spy_spec.rb failed

Tasks: TOP => default => spec
(See full trace by running task with --trace)

Done. Build script exited with: 1
```

**Comment by rentalcustard** [comment]
Mostly fixed in 8d3c42e8294d1c1a9f54, but cucumber still fails due to relative require problems...

**Comment by deepj** [comment]
Is this still a problem? I didn't get the above error

**Comment by rentalcustard** [comment]
No indeed, well spotted.
